- hosts: masters
  become: yes
  tasks:
   - name: copy /etc/kubernetes/admin.conf
     become: yes
     become_user: root
     fetch: src={{ item.src }} dest={{ item.dest }}
     with_items:
             - { src: "/etc/kubernetes/admin.conf", dest: "/tmp/" }


