apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc #important
spec:
  #storageClassName: managed-nfs-storage # we use default 
  accessModes:
    - ReadWriteOnce ### Look at default StorageClass type!!!
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deploy
  labels:
   lab: mybusybox
spec:
 replicas: 2
 selector:
  matchLabels:
   app: busybox
 template:
  metadata:
   name: busy-pod
   labels:
    app: busybox
  spec:
    volumes:
    - name: host-volume
      persistentVolumeClaim:
        claimName: my-pvc  # PVC name
    containers:
    - image: busybox
      name: busybox
      command: ["/bin/sh"]
      args: ["-c", 'sleep 3600']
      volumeMounts:
      - name: host-volume
        mountPath: /mydata
