apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: medium.howtok5678songce
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
nodeRegistration:
        #  criSocket: /var/run/dockershim.sock
  kubeletExtraArgs:
    cloud-provider: "gce"
    cloud-config: "/etc/kubernetes/cloud-config"
  taints: []
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: medium
kubernetesVersion: v1.22.3 # change
networking:
  podSubnet: 10.244.0.0/16 # Pod subnet
apiServer:
 # certSANs: #to get exteranl ip
 # - 35.187.224.267
  extraArgs:
    authorization-mode: Node,RBAC
    cloud-provider: "gce"
    cloud-config: "/etc/kubernetes/cloud-config"
  extraVolumes:
  - name: cloud
    hostPath: "/etc/kubernetes/cloud-config"
    mountPath: "/etc/kubernetes/cloud-config"
controllerManager:
  extraArgs:
    cloud-provider: "gce"
    cloud-config: "/etc/kubernetes/cloud-config"
  extraVolumes:
  - name: cloud
    hostPath: "/etc/kubernetes/cloud-config"
    mountPath: "/etc/kubernetes/cloud-config"
